config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rides
  root 'rides#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
	
	belongs_to :user
	
	validates :type, 						presence: true
	validates :request_time, 				presence: true
	validates :est_wait_time, 				presence: true
	validates :pickup_time, 				presence: true
	validates :pickup_pax, 					presence: true
	validates :pickup_address, 				presence: true
	validates :dropoff_address, 			presence: true
	validates :est_trip_duration_at_pickup, presence: true
	validates :pickups_en_route, 			presence: true
	validates :dropoffs_en_route, 			presence: true
	validates :dropoff_time, 				presence: true
	validates :cost_before_discounts, 		presence: true
	validates :cost_after_discounts, 		presence: true
	validates :actual_wait_time, 			presence: true
	validates :actual_trip_duration, 		presence: true
	validates :user_name,			 		presence: true

end

app/models/user.rb
class User < ApplicationRecord
	has_many :rides
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:type, :request_time, :est_wait_time, :pickup_time, :pickup_pax, :pickup_address, :dropoff_address, :est_trip_duration_at_pickup, :pickups_en_route, :dropoffs_en_route, :dropoff_time, :cost_before_discounts, :cost_after_discounts, :actual_wait_time, :actual_trip_duration)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = user.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = user.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = user.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = user.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :home_address, :work_address, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rideapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_for(ride) do |f| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :request_time %>
    <%= f.datetime_select :request_time %>
  </div>

  <div class="field">
    <%= f.label :est_wait_time %>
    <%= f.number_field :est_wait_time %>
  </div>

  <div class="field">
    <%= f.label :pickup_time %>
    <%= f.datetime_select :pickup_time %>
  </div>

  <div class="field">
    <%= f.label :pickup_pax %>
    <%= f.number_field :pickup_pax %>
  </div>

  <div class="field">
    <%= f.label :pickup_address %>
    <%= f.text_field :pickup_address %>
  </div>

  <div class="field">
    <%= f.label :dropoff_address %>
    <%= f.text_field :dropoff_address %>
  </div>

  <div class="field">
    <%= f.label :est_trip_duration_at_pickup %>
    <%= f.number_field :est_trip_duration_at_pickup %>
  </div>

  <div class="field">
    <%= f.label :pickups_en_route %>
    <%= f.number_field :pickups_en_route %>
  </div>

  <div class="field">
    <%= f.label :dropoffs_en_route %>
    <%= f.number_field :dropoffs_en_route %>
  </div>

  <div class="field">
    <%= f.label :dropoff_time %>
    <%= f.datetime_select :dropoff_time %>
  </div>

  <div class="field">
    <%= f.label :cost_before_discounts %>
    <%= f.text_field :cost_before_discounts %>
  </div>

  <div class="field">
    <%= f.label :cost_after_discounts %>
    <%= f.text_field :cost_after_discounts %>
  </div>

  <div class="field">
    <%= f.label :actual_wait_time %>
    <%= f.text_field :actual_wait_time %>
  </div>

  <div class="field">
    <%= f.label :actual_trip_duration %>
    <%= f.text_field :actual_trip_duration %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rides</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Request time</th>
      <th>Est wait time</th>
      <th>Pickup time</th>
      <th>Pickup pax</th>
      <th>Pickup address</th>
      <th>Dropoff address</th>
      <th>Est trip duration at pickup</th>
      <th>Pickups en route</th>
      <th>Dropoffs en route</th>
      <th>Dropoff time</th>
      <th>Cost before discounts</th>
      <th>Cost after discounts</th>
      <th>Actual wait time</th>
      <th>Actual trip duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.type %></td>
        <td><%= ride.request_time %></td>
        <td><%= ride.est_wait_time %></td>
        <td><%= ride.pickup_time %></td>
        <td><%= ride.pickup_pax %></td>
        <td><%= ride.pickup_address %></td>
        <td><%= ride.dropoff_address %></td>
        <td><%= ride.est_trip_duration_at_pickup %></td>
        <td><%= ride.pickups_en_route %></td>
        <td><%= ride.dropoffs_en_route %></td>
        <td><%= ride.dropoff_time %></td>
        <td><%= ride.cost_before_discounts %></td>
        <td><%= ride.cost_after_discounts %></td>
        <td><%= ride.actual_wait_time %></td>
        <td><%= ride.actual_trip_duration %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @ride.type %>
</p>

<p>
  <strong>Request time:</strong>
  <%= @ride.request_time %>
</p>

<p>
  <strong>Est wait time:</strong>
  <%= @ride.est_wait_time %>
</p>

<p>
  <strong>Pickup time:</strong>
  <%= @ride.pickup_time %>
</p>

<p>
  <strong>Pickup pax:</strong>
  <%= @ride.pickup_pax %>
</p>

<p>
  <strong>Pickup address:</strong>
  <%= @ride.pickup_address %>
</p>

<p>
  <strong>Dropoff address:</strong>
  <%= @ride.dropoff_address %>
</p>

<p>
  <strong>Est trip duration at pickup:</strong>
  <%= @ride.est_trip_duration_at_pickup %>
</p>

<p>
  <strong>Pickups en route:</strong>
  <%= @ride.pickups_en_route %>
</p>

<p>
  <strong>Dropoffs en route:</strong>
  <%= @ride.dropoffs_en_route %>
</p>

<p>
  <strong>Dropoff time:</strong>
  <%= @ride.dropoff_time %>
</p>

<p>
  <strong>Cost before discounts:</strong>
  <%= @ride.cost_before_discounts %>
</p>

<p>
  <strong>Cost after discounts:</strong>
  <%= @ride.cost_after_discounts %>
</p>

<p>
  <strong>Actual wait time:</strong>
  <%= @ride.actual_wait_time %>
</p>

<p>
  <strong>Actual trip duration:</strong>
  <%= @ride.actual_trip_duration %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :home_address %>
    <%= f.text_field :home_address %>
  </div>

  <div class="field">
    <%= f.label :work_address %>
    <%= f.text_field :work_address %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Home address</th>
      <th>Work address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.home_address %></td>
        <td><%= user.work_address %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @user.home_address %>
</p>

<p>
  <strong>Work address:</strong>
  <%= @user.work_address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>